// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// UBAH BARIS INI: Ambil fungsi 'config' dari dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 1. Paksa Prisma membaca file .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 2. Gunakan DIRECT_URL untuk membuat tabel di Supabase
    url: process.env["DIRECT_URL"],
  },
});